"""Turn a planned list of members into a zip archive that is sent while built.

Four decisions shape this module, and all of them come from what a collection
is, how large one is allowed to get, and what else the application does to one
while a download is running.

Nothing is compressed. MP3, JPEG, and the rest of a collection are already
compressed formats, so deflating them costs CPU and saves close to nothing.
Every member is stored verbatim.

Nothing is assembled. A collection can run to several Tonies of audio, and the
only scratch space the container has is /work, a RAM-backed tmpfs that defaults
to 2 GB. Building the whole archive anywhere before sending it would trade a
download for an out-of-memory error, so the archive is yielded in chunks and
only a chunk is ever held.

One file is open at a time. A collection may hold up to the 500-file intake
limit, so opening every member up front would run a legitimate download into
the process descriptor limit, and a client that disconnects before the first
chunk would strand every one of those handles. Opening inside the loop bounds
both at a single descriptor.

Every file is identified before and after it is read. Opening late means Forge
can replace a collection, or a delete can remove it, between one member and the
next, and holding a descriptor open does not stop a writer rewriting that same
file in place while its blocks are still being read. Without both checks the
archive would still finish, and the result would be a valid zip mixing two
versions of a story behind an index describing neither. Each member therefore
carries the identity its source had when the download was planned, and a
mismatch at either end of the read ends the stream. Because the response is
chunked, an ended stream never sends its terminating chunk, so the browser
reports an interrupted download instead of saving a plausible-looking archive.

Streaming also means the total size is unknown when the response starts, so the
reply carries no Content-Length and the browser shows an unknown-size download.
That is the accepted price for never buffering the archive.
"""
from __future__ import annotations

import os
import time
import zipfile
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO

# Read size for source files, and therefore the rough size of a yielded chunk.
CHUNK_BYTES = 512 * 1024

# The zip format cannot express a date before this one. A file copied in by
# hand can easily carry an older stamp, and losing a timestamp is a far better
# outcome than refusing to hand over the audio.
ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)


class SourceChanged(RuntimeError):
    """A source file was replaced between planning the archive and reading it."""


@dataclass(frozen=True)
class Member:
    """One archive entry: a file on disk, or literal bytes generated for it.

    `identity` is what the file was when the download was planned. It is None
    for generated bytes, which cannot be changed underneath the stream.
    """

    name: str
    source: Path | bytes
    identity: tuple[int, int, int] | None = None


def identify(path: Path) -> tuple[int, int, int]:
    """Fingerprint one file well enough to notice it being replaced."""
    stat = path.stat()
    return (stat.st_ino, stat.st_size, stat.st_mtime_ns)


def _confirm(handle: BinaryIO, member: Member) -> None:
    """Fail the stream unless the open descriptor still holds the planned file.

    Taken from the descriptor rather than the path, so it answers "is what I
    am reading still the file I planned to read", which is the question a
    rewrite in place turns into a different answer halfway through.
    """
    if member.identity is None:
        return
    stat = os.fstat(handle.fileno())
    if (stat.st_ino, stat.st_size, stat.st_mtime_ns) != member.identity:
        raise SourceChanged(
            f"{Path(handle.name).name} changed while the download was running."
        )


class _Sink:
    """A write-only file for ZipFile that hands each block back to the caller.

    Deliberately without `seek`. ZipFile probes for it, finds none, and writes
    a data descriptor after each member instead of seeking back to patch its
    header. That is what makes a single forward pass possible.
    """

    def __init__(self) -> None:
        self._blocks: list[bytes] = []
        self._offset = 0

    def write(self, data: bytes) -> int:
        block = bytes(data)
        self._blocks.append(block)
        self._offset += len(block)
        return len(block)

    def tell(self) -> int:
        return self._offset

    def flush(self) -> None:
        return None

    def drain(self) -> bytes:
        block = b"".join(self._blocks)
        self._blocks.clear()
        return block


def _member_info(name: str, mtime: float | None) -> zipfile.ZipInfo:
    """Describe one stored member, with a timestamp the zip format can hold."""
    stamp = time.localtime(mtime if mtime is not None else time.time())[:6]
    info = zipfile.ZipInfo(name, date_time=max(stamp, ZIP_EPOCH))
    info.compress_type = zipfile.ZIP_STORED
    info.external_attr = 0o644 << 16
    return info


def stream(members: Iterable[Member]) -> Iterator[bytes]:
    """Yield one zip archive of `members`, reading each source as it is needed."""
    sink = _Sink()
    with zipfile.ZipFile(sink, mode="w", compression=zipfile.ZIP_STORED, allowZip64=True) as bundle:
        for member in members:
            if isinstance(member.source, bytes):
                with bundle.open(_member_info(member.name, None), mode="w") as entry:
                    entry.write(member.source)
            else:
                with member.source.open("rb") as handle:
                    _confirm(handle, member)
                    info = _member_info(member.name, os.fstat(handle.fileno()).st_mtime)
                    with bundle.open(info, mode="w") as entry:
                        while block := handle.read(CHUNK_BYTES):
                            entry.write(block)
                            if payload := sink.drain():
                                yield payload
                    _confirm(handle, member)
            if payload := sink.drain():
                yield payload
    if payload := sink.drain():
        yield payload
